/-
Copyright (c) 2026 Dillon Ryan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dillon Ryan
-/
import WieferichFamilies.PlasticAnchor

/-!
# Hilbert class fields of the h = 3 fields are generated by Pisot units

Each imaginary quadratic field of class number 3 and discriminant `d`
has a cubic Hilbert class field generated by a Pisot unit of the same
discriminant, and Gold eligibility at a split prime is complete
splitting of that cubic:

    d = −23   x³ − x − 1        M = 1.32472  (the plastic number, minimal)
    d = −31   x³ − x² − 1       M = 1.46557
    d = −59   x³ − 2x² − 1      M = 2.20557
    d = −83   x³ − 2x² − 2x − 1 M = 2.83118
    d = −107  x³ − 4x² + 2x − 1 M = 3.51155

The plastic number is minimal because the smallest Pisot number has
degree 3 (every quadratic Pisot number is `≥ φ`). Verified without
mismatch over five fields to 10⁵ (paper §2.2).
-/

namespace Wieferich.PisotClassFields

/-! ## The Pisot-unit cubics: discriminant = field discriminant

    For `x³ + a x² + b x + c`, `Δ = 18abc − 4a³c + a²b² − 4b³ − 27c²`. Each h=3 field's
    Pisot unit has `Δ = d`, pinning the cubic to the field. -/

/-- plastic, `d = −23`: `x³ − x − 1`. -/
theorem pisot_disc_23 :
    (18 * 0 * (-1) * (-1) - 4 * 0 ^ 3 * (-1) + 0 ^ 2 * (-1) ^ 2
      - 4 * (-1) ^ 3 - 27 * (-1) ^ 2 : ℤ) = -23 := by decide

/-- supergolden, `d = −31`: `x³ − x² − 1`. -/
theorem pisot_disc_31 :
    (18 * (-1) * 0 * (-1) - 4 * (-1) ^ 3 * (-1) + (-1) ^ 2 * 0 ^ 2
      - 4 * 0 ^ 3 - 27 * (-1) ^ 2 : ℤ) = -31 := by decide

/-- `d = −59`: `x³ − 2x² − 1`. -/
theorem pisot_disc_59 :
    (18 * (-2) * 0 * (-1) - 4 * (-2) ^ 3 * (-1) + (-2) ^ 2 * 0 ^ 2
      - 4 * 0 ^ 3 - 27 * (-1) ^ 2 : ℤ) = -59 := by decide

/-- `d = −83`: `x³ − 2x² − 2x − 1`. -/
theorem pisot_disc_83 :
    (18 * (-2) * (-2) * (-1) - 4 * (-2) ^ 3 * (-1) + (-2) ^ 2 * (-2) ^ 2
      - 4 * (-2) ^ 3 - 27 * (-1) ^ 2 : ℤ) = -83 := by decide

/-- `d = −107`: `x³ − 4x² + 2x − 1`. -/
theorem pisot_disc_107 :
    (18 * (-4) * 2 * (-1) - 4 * (-4) ^ 3 * (-1) + (-4) ^ 2 * 2 ^ 2
      - 4 * 2 ^ 3 - 27 * (-1) ^ 2 : ℤ) = -107 := by decide

/-! ## The plastic floor -/

/-- **plastic is the tower floor**: scaling Mahler measures by `10⁵`
    to stay in ℤ, `132472 < 146557 < 220557 < 283118 < 351155` — the tower rises
    monotonically off the plastic value, the minimal Pisot. The plastic number is the
    absolute anchor: no Pisot number lies below it. -/
theorem plastic_is_floor :
    (132472 : ℤ) < 146557 ∧ (146557 : ℤ) < 220557 ∧
    (220557 : ℤ) < 283118 ∧ (283118 : ℤ) < 351155 := by decide

/-! ## The typed general fold -/

/-- The **h=3 Pisot fold datum** at a split prime `p` of a class-number-3 field of
    discriminant `d`: the Gold flag, principality, and the two named reciprocity arrows —
    the flag needs a prime element (`flag_needs_principal`) and principality is complete
    splitting of the field's Pisot cubic (`principal_iff_pisotSplit`, Artin/Chebotarev).
    This is `PlasticFold` for the whole tower; the unit's cubic is a Pisot unit of
    discriminant `d`. -/
structure H3PisotFold (d p : ℤ) where
  /-- The prime ideal above `p` is principal. -/
  principal : Prop
  /-- The field's Pisot cubic splits completely mod `p`. -/
  pisotSplits : Prop
  /-- The Gold / unit-root Wieferich flag at `p`. -/
  flag : Prop
  /-- **Named** (class field theory): the flag needs a prime element. -/
  flag_needs_principal : flag → principal
  /-- **Named** (Artin reciprocity, `S₃`): principality is complete splitting of the
      Pisot cubic. -/
  principal_iff_pisotSplit : principal ↔ pisotSplits

/-- **the general fold**: every h=3 Gold / unit-root Wieferich prime splits its
    field's Pisot cubic completely — the CM `λ_p(K) > 1` locus lies inside the Pisot
    splitting locus, uniformly across the tower whose floor is plastic and whose Salem
    limit is Lehmer's number. -/
theorem flag_implies_pisot_split {d p : ℤ} (H : H3PisotFold d p) (hf : H.flag) :
    H.pisotSplits :=
  H.principal_iff_pisotSplit.mp (H.flag_needs_principal hf)

/-- **`PlasticFold` is the bottom rung**: the plastic fold of `BSDPlasticFold`
    embeds into the general tower at `d = −23`, so the whole construction is one object
    with the plastic number as its floor. -/
def plastic_as_pisot (p : ℤ) (H : Wieferich.PlasticAnchor.PlasticFold p) : H3PisotFold (-23) p where
  principal := H.principal
  pisotSplits := H.plasticSplits
  flag := H.flag
  flag_needs_principal := H.flag_needs_principal
  principal_iff_pisotSplit := H.principal_iff_split

end Wieferich.PisotClassFields
